version: '3.3'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    volumes:
      # Logging
      - ./nginx/log:/var/log/nginx/
      - ./:/var/www/html/
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db_bocao'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8081:8080
  php-fpm:
    image: php:8.0.23-fpm
    volumes:
      - .:/var/www/html/
volumes:
  db_data: {}
